Fix #26
neelkamath/time-bend-web pull request #27
Opened 2020-10-24 19:28 UTC by AshtrayShetty

Required a tiny bit of position changes. Seems to work on microsoft edge, firefox, chrome and brave. Let me know if some issue comes up.

2020-10-25 04:10 UTC, neelkamath requested changes

2020-10-25 04:10 UTC, neelkamath commented on src/components/DayTime.tsx
> +            <label style={{textAlign: 'left'}}>
Styling should be separate from the HTML/JS. Create a styled component similar to `Span` below this function. Maybe call it `Label`.

2020-10-25 04:10 UTC, neelkamath commented on src/components/DayTime.tsx
> +// padding-right: 1em;
There's no need to comment out old code - you can simply delete it.

2020-10-26 03:38 UTC, AshtrayShetty commented
made the changes that were requested :)

2020-10-26 04:41 UTC, neelkamath requested changes

2020-10-26 04:41 UTC, neelkamath commented on src/components/DayTime.tsx
> +const Label= styled.label`
I'd expect your editor to autoformat the code upon save/commit but otherwise you'll need to manually format it. Put a space before the `=` sign.

2020-10-27 03:44 UTC, AshtrayShetty commented
Changes made as per requested

2020-10-27 04:29 UTC, neelkamath commented
No need to comment that changes were made since GitHub creates a notification when a commit is made since I'm reviewing it.

2020-10-27 04:32 UTC, neelkamath commented
There appears to be a regression.

Here's how the site looked in Chrome before this update:
<img width="1440" alt="Screen Shot 2020-10-27 at 10 00 40 AM" src="https://user-images.githubusercontent.com/24778804/97257253-63b6e600-183b-11eb-82d6-462fcaccf82f.png">

Here's how it looks now:
<img width="1440" alt="Screen Shot 2020-10-27 at 10 00 37 AM" src="https://user-images.githubusercontent.com/24778804/97257264-6a455d80-183b-11eb-8316-364674f08555.png">

And Safari is still unstyled:
<img width="1440" alt="Screen Shot 2020-10-27 at 10 00 50 AM" src="https://user-images.githubusercontent.com/24778804/97257276-716c6b80-183b-11eb-89bc-80aff15d3488.png">

2020-11-02 15:20 UTC, neelkamath commented
Maybe next time.

2020-11-02 15:20 UTC, closed without merging